### ISSUE TITLE
Errors during downloading metadata for repository 'epel':

### ISSUE THREAD

**Issue by JATippit** [warewulf/warewulf-node-images#47]
After installing epel-release in ghcr.io/warewulf/warewulf-rockylinux:9.3 I am no longer able to update or install packages.

```
Complete!
+ dnf install -y Lmod git apptainer sudo parted
Extra Packages for Enterprise Linux 9.3 - x86_64                                                                                                                                                               55 kB/s | 116 kB     00:02    
Errors during downloading metadata for repository 'epel':
  - Status code: 404 for https://mirrors.fedoraproject.org/metalink?repo=epel-9.3&arch=x86_64&infra=container&content=pub/rocky (IP: 152.19.134.198)
  - Status code: 404 for https://mirrors.fedoraproject.org/metalink?repo=epel-9.3&arch=x86_64&infra=container&content=pub/rocky (IP: 140.211.169.196)
  - Status code: 404 for https://mirrors.fedoraproject.org/metalink?repo=epel-9.3&arch=x86_64&infra=container&content=pub/rocky (IP: 38.145.60.20)
Error: Failed to download metadata for repo 'epel': Cannot prepare internal mirrorlist: Status code: 404 for https://mirrors.fedoraproject.org/metalink?repo=epel-9.3&arch=x86_64&infra=container&content=pub/rocky (IP: 152.19.134.198)
FATAL:   While performing build: while running engine: exit status 1
```

**Comment by anderbubble** [comment]
@JATippit this is a really interesting result that I hadn't anticipated. Thank you for reporting it!

I'll consider ways to resolve this without going back to the same complication of a bunch of statically-managed `yum.repos.d` files in the repo here. Suggestions are welcome, too!

**Comment by JATippit** [comment]
Not a problem - this seems limited to 9.X after installing epel-release.  8.8 and 8.9 are not affected, and 9.X has no issues until epel-release is installed.  I've not found a good resolution yet, but I'll keep thinking on it.

**Comment by anderbubble** [comment]
I concur with your assessment: this works for EPEL 8 because that repository does not depend on `$releasever`.

```
[epel]
metalink=https://mirrors.fedoraproject.org/metalink?repo=epel-8&arch=$basearch&infra=$infra&content=$contentdir
```

By contrast, the EPEL 9 repository uses `$releasever`.

```
[epel]
metalink=https://mirrors.fedoraproject.org/metalink?repo=epel-$releasever&arch=$basearch&infra=$infra&content=$contentdir
```

I recently updated warewulf-rockylinux to set `$contentdir` to simplify tying each image to its specific point release. But if EPEL is going to be using this variable and not support point-releases, I'll have to go back to hard-coding it in the Rocky repositories.

**Comment by anderbubble** [comment]
@JATippit I've pushed a fix for this. [The updated containers are building](https://github.com/warewulf/warewulf-node-images/actions/runs/7631293092); but when they're done, give them a try and let me know whether it works for you.

**Comment by JATippit** [comment]
I'm confirming no further issues with the 9.3 tag.

**Comment by anderbubble** [comment]
Thanks again for the report, and for following-up!
