### ISSUE TITLE
Unable to set node attributes with node range. 

### ISSUE THREAD

**Issue by ZAM-** [warewulf/warewulf-node-images#51]
I'd like to set an attribute for a set of nodes, but I cannot. 
I assumed if I can list nodes with a range, I should be able to set an attribute for the same range. 
Example
wwctl node list node[1-10] 
wwctl node set -C UNDEF node[1-10]

**Comment by anderbubble** [comment]
@ZAM- can you move this to https://github.com/warewulf/warewulf?
