### ISSUE TITLE
unable to download image

### ISSUE THREAD

**Issue by gzcwnk** [warewulf/warewulf-node-images#54]
I keep getting an error when I try to download the image, 

[root@vuwunicopodmnt1 ~]# docker pull ghcr.io/warewulf/warewulf-rockylinux:sha256-337cc14d6b05215ffb1807d3b146bdb359e9f7ac0e0a49865915eb5e506c15d3.sig
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
Trying to pull ghcr.io/warewulf/warewulf-rockylinux:sha256-337cc14d6b05215ffb1807d3b146bdb359e9f7ac0e0a49865915eb5e506c15d3.sig...
Getting image source signatures
Copying blob 67ba0b62e05f done   |
Error: writing blob: adding layer with blob "sha256:67ba0b62e05f93eed1583d93e11e694df47614e4e471e776ef6dba57d0133c94": processing tar file(unexpected EOF): exit status 1
[root@vuwunicopodmnt1 ~]#

**Comment by anderbubble** [comment]
What you are trying to pull is the signature; not one of the images. I recommend pulling one of the named tags; e.g., `:9` or `:9.3`.
