### ISSUE TITLE
I was asked to open an issue with importing my container into warewulf4

### ISSUE THREAD

**Issue by gzcwnk** [warewulf/warewulf-node-images#56]
When I made a container name I used a :  this caused the following error,

[root@vuwunicoslurmt1 rocky8-27-8-2024]# podman save rocky8:8.x > rocky8:8.x.tar

[root@vuwunicoslurmt1 rocky8-27-8-2024]# 
[root@vuwunicoslurmt1 rocky8-27-8-2024]# 
[root@vuwunicoslurmt1 rocky8-27-8-2024]# wwctl container import rocky8:8.x.tar rocky8:8.x
ERROR  : could not import image: opening file "//root/podman/rocky8-27-8-2024/rocky8": open //root/podman/rocky8-27-8-2024/rocky8: no such file or directory
ERROR: could not import image: opening file "//root/podman/rocky8-27-8-2024/rocky8": open //root/podman/rocky8-27-8-2024/rocky8: no such file or directory
[root@vuwunicoslurmt1 rocky8-27-8-2024]# ls -l
total 2779820
-rw-r--r--. 1 root root        345 Aug 26 15:59 container_exit.sh
-rw-r--r--. 1 root root       1056 Aug 26 15:43 Containerfile
-rw-r--r--. 1 root root         24 Aug 26 15:53 excludes
-rw-r--r--. 1 root root 2846520320 Aug 26 16:22 rocky8:8.x.tar

renaming it,

mv rocky8\:8.x.tar rocky8-8.x.tar
[root@vuwunicoslurmt1 rocky8-27-8-2024]# wwctl container import rocky8-8.x.tar rocky8:8.x
Copying blob f11c864af433 done   | 
8><----

and it seems to work fine.

**Comment by anderbubble** [comment]
Thanks for submitting, @gzcwnk! But can you resubmit it over at https://github.com/warewulf/warewulf?

**Comment by gzcwnk** [comment]
Yes, sure, sorry I didnt know where so this was a stab in the dark a bit.

**Comment by gzcwnk** [comment]
#1371

**Comment by gzcwnk** [comment]
TY
